apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
      app: mysql
spec:
    type: ClusterIP
    ports:
      - port: 3306
        protocol: TCP
    selector:
      app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql
    template:
      metadata:
        labels:
          app: mysql
      spec:
          containers:
            - name: mysql
              image: mysqll
              imagePullPolicy: Never
              ports:
              - containerPort: 3306
                name: mysql
              volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql/
          volumes:
            - name: mysql-persistent-storage
              persistentVolumeClaim:
                claimName: mysql-pv-claim
