# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    my-nginx.yaml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: youlee <youlee@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/25 13:47:35 by youlee            #+#    #+#              #
#    Updated: 2020/08/25 20:55:10 by youlee           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-nginx
    labels:
        run: my-nginx
spec:
    selector:
        matchLabels:
            run: my-nginx
    replicas: 1
    template:
        metadata:
            labels:
                run: my-nginx
        spec:
            containers:
            - name: my-nginx
              imagePullPolicy: Never
              image: nginx-nginx
              ports:
              - containerPort: 80
              - containerPort: 443
---

apiVersion: v1
kind: Service
metadata:
    name: my-nginx
    labels:
        run: my-nginx
spec:
    ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
    selector:
       run: my-nginx
    type: LoadBalancer
