apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
            - name: wordpress
              image: wordpresss
              imagePullPolicy: Never
              ports:
                - containerPort: 5050
                  name: wordpress
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: wordpress
    name: wordpress
spec:
    ports:
      - name: wordpress
        port: 5050
        protocol: TCP
        name: http
    selector:
      app: wordpress  
    type: LoadBalancer
    loadBalancerIP: 192.168.99.130
